POST http://localhost:5000/users
Content-Type: application/json


{
  "firstName": "Mark",
  "lastName": "Doe",
  "email": "markaszxczdsfa@doe.com",
  "password": "Password123#"
}


POST http://localhost:5000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiYWJoaTExMUBnbWFpbC5jb20iLCJpYXQiOjE3ODUwNDgwMjUsImV4cCI6MTc4NTA1MTYyNSwiYXVkIjoibG9jYWxob3N0OjUwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NTAwMCJ9.usM2FPHDco9JOuOOxlYu1ZceuEDcRn6Oe3URxtOgcWs

{
"users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "mark@doe.com",
      "password": "Password123#"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tom@doe.com",
      "password": "Password123#"
    }
  ]
}

